# every app should have its own urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import delete_image

app_name = 'job'  # This is the app namespace

urlpatterns = [
    path('', views.job_list), # returns all jobs (job_list) it will be triggered when the user types localhost:8000/jobs
    path('<int:job_id>', views.job_detail, name='job_detail'), # returns a single job
    path('admin/delete_image/<int:job_id>/', delete_image, name='delete_image'),

]
""""""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    '''
Purpose
Serve Media Files During Development: When DEBUG is True, this line ensures that media files 
(uploaded by users or generated by the application) are served by Django's development server. 
This is useful during development because it allows you to see and interact with media files 
without needing a separate web server to serve them.
    '''